# INTERVAL_SRV API TEST

# CREATE PLANIFICATION
POST http://localhost:3200/events/listeners HTTP/1.1
content-type: application/json

{
    "type":"planification.create",
    "payload":{"ref":"asdasd", "data":{
        "start": "1654201399212",
        "end": "1654201424990",
        "count":3,
        "date": "1654199829960",
        "plan":["9:04", "10:15", "20:02"],
        "name":"test"
        
    }},
    "correlationId": "asdaasdfgh",
    "origin": "test"
}

###


# DELETE PLANIFICATION
POST http://localhost:3200/events/listeners HTTP/1.1
content-type: application/json

{
    "type":"planification.delete",
    "payload":{"ref":"asdasd", "_id":"62991b57a328ce06a7bb8659"},
    "correlationId": "asdaasdfgh",
    "origin": "test"
}