# INTERVAL_SRV API TEST

# CREATE PLANIFICATION
POST http://localhost:3200/events/listeners HTTP/1.1
content-type: application/json

{
    "type":"planification.create",
    "payload":{"ref":"asdasd", "data":{
        "start": 1654322400000,
        "end": 1654354800000,
        "count":50,
        "date": 1654322400000,
        "name":"test"
        
    }},
    "correlationId": "asdaasdfgh",
    "origin": "test"
}

###


# DELETE PLANIFICATION
POST http://localhost:3200/events/listeners HTTP/1.1
content-type: application/json

{
    "type":"planification.delete",
    "payload":{"ref":"asdasd", "_id":"62991b57a328ce06a7bb8659"},
    "correlationId": "asdaasdfgh",
    "origin": "test"
}