# USER_SRV API TEST

# LOGIN
POST http://localhost:3100/usr/login HTTP/1.1
content-type: application/json

{
    "email":"andrei.nechita95@gmail.com",
    "password":"1234"
}

###

#  SYNC REGISTER
POST http://localhost:3100/usr/register HTTP/1.1
content-type: application/json

{   
    "firstName": "Dinu-Andrei",
    "lastName": "Nechita",
    "email":"andrei.nechitaw95@gmail.com",
    "password":"1234",
    "confirmedPassword":"1234"
}

###

# SYNC DELETE USER
DELETE http://localhost:3100/usr/delete/6294023007cf2e4bf9aa0cbe HTTP/1.1
content-type: application/json


###

#ASYNC REGISTER

POST http://localhost:3100/events/listeners HTTP/1.1
content-type: application/json

{   
    "type":"user.create",
    "origin": "local",
    "payload":{
        "firstName": "Dinu-Andrei",
        "lastName": "Nechita",
        "email":"andrei.nechita22295@gmail.com",
        "password":"1234",
        "confirmedPassword":"1234"
    },
    "correlationId":"test"
}


###

#ASYNC REGISTER

POST http://localhost:3100/events/listeners HTTP/1.1
content-type: application/json

{   
    "type":"user.delete",
    "origin": "local",
    "payload":"629a160b464829361fec65b6",
    "correlationId":"delete-test"
}
